# General settings
name: 'comm20'      # Warning: 'debug' and 'test' are reserved name that have a special behavior

wandb: 'online'             # online | offline | disabled
gpus: 1                     # Multi-gpu is not implemented on this branch


resume: null            # If resume, path to ckpt file from outputs directory in main directory
test_only: null         # Use absolute path

check_val_every_n_epochs: 1000
sample_every_val: 10
val_check_interval: null
samples_to_generate: 20       # We advise to set it to 2 x batch_size maximum
samples_to_save: 20
chains_to_save: 1
log_every_steps: 50
number_chain_steps: 50        # Number of frames in each gif

final_model_samples_to_generate: 30
#final_model_samples_to_generate: 3000
final_model_samples_to_save: 30
final_model_chains_to_save: 20
#final_model_samples_to_generate: 3
#final_model_samples_to_save: 2
#final_model_chains_to_save: 1

evaluate_all_checkpoints: False